import logging
from app.ai.providers.base import BaseAIProvider

logger = logging.getLogger("creatormind")


class MockProvider(BaseAIProvider):
    """Development-only provider. Returns deterministic fixture responses."""

    def generate(self, prompt: str, **kwargs) -> str:
        logger.info("MockProvider.generate() called — returning fixture response.")
        return (
            "mock response: This is a placeholder generated by CreatorMind MockProvider. "
            "Switch AI_PROVIDER=granite in .env to enable IBM Granite."
        )
        
    async def stream_generate(self, prompt: str, **kwargs):
        import asyncio
        logger.info("MockProvider.stream_generate() called.")
        text = "mock response: This is a placeholder generated by CreatorMind MockProvider. Switch AI_PROVIDER=granite in .env to enable IBM Granite."
        for word in text.split(" "):
            yield word + " "
            await asyncio.sleep(0.05)

    def chat(self, messages: list[dict], **kwargs) -> str:
        logger.info("MockProvider.chat() called — returning fixture chat response.")
        return "mock chat response: CreatorMind is running in development mode."

    async def stream_chat(self, messages: list[dict], **kwargs):
        import asyncio
        logger.info("MockProvider.stream_chat() called.")
        text = "mock chat response: CreatorMind is running in development mode."
        for word in text.split(" "):
            yield word + " "
            await asyncio.sleep(0.05)
